import numpy as np
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, asdict
from datetime import datetime
import json


@dataclass
class Evidence:
    """Piece of evidence in an investigation"""
    
    evidence_id: str
    evidence_type: str  # satellite_image, ground_photo, document, witness_report, etc.
    source: str
    timestamp: str
    location: Dict
    description: str
    confidence: float
    metadata: Dict
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            "evidence_id": self.evidence_id,
            "evidence_type": self.evidence_type,
            "source": self.source,
            "timestamp": self.timestamp,
            "location": self.location,
            "description": self.description,
            "confidence": self.confidence,
            "metadata": self.metadata
        }


@dataclass
class EvidenceChain:
    """Chain of evidence linking changes to causes"""
    
    chain_id: str
    change_event_id: int
    evidence: List[Evidence]
    chain_confidence: float
    created_at: str
    updated_at: str
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            "chain_id": self.chain_id,
            "change_event_id": self.change_event_id,
            "evidence": [e.to_dict() for e in self.evidence],
            "chain_confidence": self.chain_confidence,
            "created_at": self.created_at,
            "updated_at": self.updated_at
        }


@dataclass
class InvestigationReport:
    """Report generated by investigation assistant"""
    
    report_id: str
    change_event_id: int
    summary: str
    findings: List[str]
    conclusions: List[str]
    recommendations: List[str]
    evidence_chain: EvidenceChain
    risk_assessment: Dict
    generated_at: str
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            "report_id": self.report_id,
            "change_event_id": self.change_event_id,
            "summary": self.summary,
            "findings": self.findings,
            "conclusions": self.conclusions,
            "recommendations": self.recommendations,
            "evidence_chain": self.evidence_chain.to_dict(),
            "risk_assessment": self.risk_assessment,
            "generated_at": self.generated_at
        }


class InvestigationAssistant:
    """AI-powered investigation assistant for change events"""
    
    def __init__(self):
        self.evidence_chains = {}
        self.investigation_reports = {}
    
    def create_evidence_chain(
        self,
        change_event_id: int,
        initial_evidence: List[Dict]
    ) -> EvidenceChain:
        """
        Create an evidence chain for a change event.
        
        Args:
            change_event_id: ID of the change event
            initial_evidence: List of initial evidence items
        
        Returns:
            EvidenceChain object
        """
        chain_id = f"chain_{change_event_id}_{datetime.utcnow().timestamp()}"
        
        evidence_objects = [
            Evidence(
                evidence_id=e.get("evidence_id", f"ev_{i}"),
                evidence_type=e.get("evidence_type", "unknown"),
                source=e.get("source", "unknown"),
                timestamp=e.get("timestamp", datetime.utcnow().isoformat()),
                location=e.get("location", {}),
                description=e.get("description", ""),
                confidence=e.get("confidence", 0.5),
                metadata=e.get("metadata", {})
            )
            for i, e in enumerate(initial_evidence)
        ]
        
        # Calculate chain confidence
        chain_confidence = self._calculate_chain_confidence(evidence_objects)
        
        chain = EvidenceChain(
            chain_id=chain_id,
            change_event_id=change_event_id,
            evidence=evidence_objects,
            chain_confidence=chain_confidence,
            created_at=datetime.utcnow().isoformat(),
            updated_at=datetime.utcnow().isoformat()
        )
        
        self.evidence_chains[chain_id] = chain
        return chain
    
    def add_evidence(
        self,
        chain_id: str,
        evidence: Dict
    ) -> EvidenceChain:
        """
        Add evidence to an existing chain.
        
        Args:
            chain_id: ID of the evidence chain
            evidence: New evidence item
        
        Returns:
            Updated EvidenceChain
        """
        if chain_id not in self.evidence_chains:
            raise ValueError(f"Evidence chain {chain_id} not found")
        
        chain = self.evidence_chains[chain_id]
        
        new_evidence = Evidence(
            evidence_id=evidence.get("evidence_id", f"ev_{len(chain.evidence)}"),
            evidence_type=evidence.get("evidence_type", "unknown"),
            source=evidence.get("source", "unknown"),
            timestamp=evidence.get("timestamp", datetime.utcnow().isoformat()),
            location=evidence.get("location", {}),
            description=evidence.get("description", ""),
            confidence=evidence.get("confidence", 0.5),
            metadata=evidence.get("metadata", {})
        )
        
        chain.evidence.append(new_evidence)
        chain.chain_confidence = self._calculate_chain_confidence(chain.evidence)
        chain.updated_at = datetime.utcnow().isoformat()
        
        return chain
    
    def _calculate_chain_confidence(self, evidence: List[Evidence]) -> float:
        """Calculate overall confidence of evidence chain"""
        if not evidence:
            return 0.0
        
        # Weight by evidence type
        type_weights = {
            "satellite_image": 0.9,
            "ground_photo": 0.8,
            "document": 0.7,
            "witness_report": 0.5,
            "sensor_data": 0.85,
            "unknown": 0.3
        }
        
        weighted_confidence = 0.0
        total_weight = 0.0
        
        for ev in evidence:
            weight = type_weights.get(ev.evidence_type, 0.3)
            weighted_confidence += ev.confidence * weight
            total_weight += weight
        
        return weighted_confidence / total_weight if total_weight > 0 else 0.0
    
    def generate_investigation_report(
        self,
        change_event_id: int,
        change_data: Dict,
        evidence_chain: Optional[EvidenceChain] = None,
        gis_context: Optional[Dict] = None,
        classification: Optional[Dict] = None
    ) -> InvestigationReport:
        """
        Generate an investigation report for a change event.
        
        Args:
            change_event_id: ID of the change event
            change_data: Change detection data
            evidence_chain: Optional evidence chain
            gis_context: Optional GIS context
            classification: Optional classification results
        
        Returns:
            InvestigationReport object
        """
        report_id = f"report_{change_event_id}_{datetime.utcnow().timestamp()}"
        
        # Generate summary
        summary = self._generate_summary(change_data, classification, gis_context)
        
        # Generate findings
        findings = self._generate_findings(change_data, evidence_chain, gis_context, classification)
        
        # Generate conclusions
        conclusions = self._generate_conclusions(findings, evidence_chain)
        
        # Generate recommendations
        recommendations = self._generate_recommendations(findings, conclusions, gis_context)
        
        # Assess risk
        risk_assessment = self._assess_investigation_risk(change_data, classification, gis_context)
        
        # Use provided chain or create empty one
        if evidence_chain is None:
            evidence_chain = EvidenceChain(
                chain_id="temp",
                change_event_id=change_event_id,
                evidence=[],
                chain_confidence=0.0,
                created_at=datetime.utcnow().isoformat(),
                updated_at=datetime.utcnow().isoformat()
            )
        
        report = InvestigationReport(
            report_id=report_id,
            change_event_id=change_event_id,
            summary=summary,
            findings=findings,
            conclusions=conclusions,
            recommendations=recommendations,
            evidence_chain=evidence_chain,
            risk_assessment=risk_assessment,
            generated_at=datetime.utcnow().isoformat()
        )
        
        self.investigation_reports[report_id] = report
        return report
    
    def _generate_summary(
        self,
        change_data: Dict,
        classification: Optional[Dict],
        gis_context: Optional[Dict]
    ) -> str:
        """Generate investigation summary"""
        parts = []
        
        # Change description
        change_area = change_data.get("change_area", 0)
        change_percentage = change_data.get("change_percentage", 0)
        parts.append(
            f"A change event affecting {change_area:.0f} pixels ({change_percentage:.1f}%) was detected."
        )
        
        # Classification
        if classification:
            is_human = classification.get("is_human_induced", False)
            activity = classification.get("activity_type", "unknown")
            parts.append(
                f"The change is classified as {'human-induced' if is_human else 'natural'}, "
                f"with suspected activity type: {activity}."
            )
        
        # Location context
        if gis_context:
            country = gis_context.get("country", "unknown")
            region = gis_context.get("region", "unknown")
            parts.append(f"The change occurred in {region}, {country}.")
            
            if gis_context.get("is_protected_area"):
                parts.append(
                    f"The area is a protected area ({gis_context.get('protected_area_type')})."
                )
        
        return " ".join(parts)
    
    def _generate_findings(
        self,
        change_data: Dict,
        evidence_chain: Optional[EvidenceChain],
        gis_context: Optional[Dict],
        classification: Optional[Dict]
    ) -> List[str]:
        """Generate investigation findings"""
        findings = []
        
        # Change magnitude
        change_area = change_data.get("change_area", 0)
        if change_area > 10000:
            findings.append("Large-scale change detected (>10,000 pixels)")
        elif change_area > 1000:
            findings.append("Medium-scale change detected (>1,000 pixels)")
        else:
            findings.append("Small-scale change detected")
        
        # Temporal pattern
        duration = change_data.get("duration_days", 0)
        if duration > 0:
            if duration < 7:
                findings.append("Change occurred rapidly (<7 days)")
            elif duration < 30:
                findings.append("Change occurred over moderate time period")
            else:
                findings.append("Change occurred gradually (>30 days)")
        
        # Classification findings
        if classification:
            if classification.get("is_human_induced"):
                findings.append("Change appears to be human-caused")
                activity = classification.get("activity_type")
                if activity and activity != "unknown":
                    findings.append(f"Activity type identified as: {activity}")
            else:
                findings.append("Change appears to be natural")
        
        # GIS context findings
        if gis_context:
            if gis_context.get("is_protected_area"):
                findings.append("Change occurred in protected area - potential regulatory violation")
            
            pop_density = gis_context.get("population_density", 0)
            if pop_density > 1000:
                findings.append("High population density area - potential social impact")
            
            if gis_context.get("proximity_to_water", 10000) < 1000:
                findings.append("Proximity to water body - potential environmental impact")
        
        # Evidence chain findings
        if evidence_chain and evidence_chain.evidence:
            findings.append(f"Evidence chain contains {len(evidence_chain.evidence)} items")
            findings.append(f"Evidence chain confidence: {evidence_chain.chain_confidence:.1%}")
            
            # Check evidence types
            evidence_types = set(e.evidence_type for e in evidence_chain.evidence)
            if "satellite_image" in evidence_types:
                findings.append("Satellite imagery evidence available")
            if "ground_photo" in evidence_types:
                findings.append("Ground photography evidence available")
            if "document" in evidence_types:
                findings.append("Documentary evidence available")
        
        return findings
    
    def _generate_conclusions(
        self,
        findings: List[str],
        evidence_chain: Optional[EvidenceChain]
    ) -> List[str]:
        """Generate investigation conclusions"""
        conclusions = []
        
        # Based on findings
        if "large-scale change" in " ".join(findings).lower():
            conclusions.append("The scale of change suggests significant impact requiring attention")
        
        if "human-caused" in " ".join(findings).lower():
            conclusions.append("Human activity is the likely cause of this change")
        
        if "protected area" in " ".join(findings).lower():
            conclusions.append("The location in a protected area raises regulatory concerns")
        
        if evidence_chain and evidence_chain.chain_confidence > 0.7:
            conclusions.append("Strong evidence supports the investigation findings")
        elif evidence_chain and evidence_chain.chain_confidence > 0.4:
            conclusions.append("Moderate evidence supports the investigation findings")
        else:
            conclusions.append("Limited evidence available - further investigation recommended")
        
        return conclusions
    
    def _generate_recommendations(
        self,
        findings: List[str],
        conclusions: List[str],
        gis_context: Optional[Dict]
    ) -> List[str]:
        """Generate investigation recommendations"""
        recommendations = []
        
        # Based on findings
        if "large-scale change" in " ".join(findings).lower():
            recommendations.append("Conduct comprehensive impact assessment")
        
        if "protected area" in " ".join(findings).lower():
            recommendations.extend([
                "Notify relevant authorities",
                "Review compliance with protected area regulations"
            ])
        
        if "human-caused" in " ".join(findings).lower():
            recommendations.extend([
                "Investigate responsible parties",
                "Review permits and authorizations"
            ])
        
        # Based on GIS context
        if gis_context and gis_context.get("proximity_to_water", 10000) < 1000:
            recommendations.append("Assess water quality and aquatic ecosystem impact")
        
        if gis_context and gis_context.get("population_density", 0) > 1000:
            recommendations.append("Engage with local communities")
        
        # General recommendations
        recommendations.extend([
            "Continue monitoring the area for further changes",
            "Document all evidence for potential legal proceedings",
            "Consider preventive measures for similar areas"
        ])
        
        return recommendations
    
    def _assess_investigation_risk(
        self,
        change_data: Dict,
        classification: Optional[Dict],
        gis_context: Optional[Dict]
    ) -> Dict:
        """Assess risk level for investigation"""
        risk_score = 0.0
        risk_factors = []
        
        # Change area risk
        change_area = change_data.get("change_area", 0)
        if change_area > 10000:
            risk_score += 0.3
            risk_factors.append("Large change area")
        elif change_area > 5000:
            risk_score += 0.2
            risk_factors.append("Medium change area")
        
        # Human activity risk
        if classification and classification.get("is_human_induced"):
            risk_score += 0.3
            risk_factors.append("Human-induced change")
        
        # Protected area risk
        if gis_context and gis_context.get("is_protected_area"):
            risk_score += 0.4
            risk_factors.append("Protected area location")
        
        # Population risk
        if gis_context and gis_context.get("population_density", 0) > 1000:
            risk_score += 0.2
            risk_factors.append("High population density")
        
        # Determine risk level
        if risk_score >= 0.7:
            level = "critical"
        elif risk_score >= 0.5:
            level = "high"
        elif risk_score >= 0.3:
            level = "medium"
        else:
            level = "low"
        
        return {
            "risk_score": float(risk_score),
            "risk_level": level,
            "risk_factors": risk_factors
        }
    
    def analyze_evidence_patterns(
        self,
        chain_id: str
    ) -> Dict:
        """
        Analyze patterns in an evidence chain.
        
        Args:
            chain_id: ID of the evidence chain
        
        Returns:
            Dict with pattern analysis
        """
        if chain_id not in self.evidence_chains:
            raise ValueError(f"Evidence chain {chain_id} not found")
        
        chain = self.evidence_chains[chain_id]
        
        # Analyze evidence types
        type_counts = {}
        for ev in chain.evidence:
            type_counts[ev.evidence_type] = type_counts.get(ev.evidence_type, 0) + 1
        
        # Analyze temporal distribution
        timestamps = []
        for ev in chain.evidence:
            try:
                timestamps.append(datetime.fromisoformat(ev.timestamp))
            except:
                pass
        
        temporal_span = None
        if timestamps:
            temporal_span = (max(timestamps) - min(timestamps)).total_seconds() / 86400
        
        # Analyze sources
        sources = set(ev.source for ev in chain.evidence)
        
        # Analyze confidence distribution
        confidences = [ev.confidence for ev in chain.evidence]
        avg_confidence = np.mean(confidences) if confidences else 0
        
        return {
            "chain_id": chain_id,
            "total_evidence": len(chain.evidence),
            "evidence_type_breakdown": type_counts,
            "unique_sources": len(sources),
            "temporal_span_days": float(temporal_span) if temporal_span else None,
            "average_confidence": float(avg_confidence),
            "chain_confidence": chain.chain_confidence,
            "analysis_date": datetime.utcnow().isoformat()
        }
    
    def get_evidence_chain(self, chain_id: str) -> Optional[EvidenceChain]:
        """Get an evidence chain by ID"""
        return self.evidence_chains.get(chain_id)
    
    def get_investigation_report(self, report_id: str) -> Optional[InvestigationReport]:
        """Get an investigation report by ID"""
        return self.investigation_reports.get(report_id)
    
    def export_evidence_chain(self, chain: EvidenceChain) -> str:
        """Export evidence chain as JSON"""
        return json.dumps(chain.to_dict(), indent=2)
    
    def import_evidence_chain(self, json_data: str) -> EvidenceChain:
        """Import evidence chain from JSON"""
        data = json.loads(json_data)
        
        evidence = [
            Evidence(**ev)
            for ev in data["evidence"]
        ]
        
        return EvidenceChain(
            chain_id=data["chain_id"],
            change_event_id=data["change_event_id"],
            evidence=evidence,
            chain_confidence=data["chain_confidence"],
            created_at=data["created_at"],
            updated_at=data["updated_at"]
        )
    
    def export_investigation_report(self, report: InvestigationReport) -> str:
        """Export investigation report as JSON"""
        return json.dumps(report.to_dict(), indent=2)
    
    def import_investigation_report(self, json_data: str) -> InvestigationReport:
        """Import investigation report from JSON"""
        data = json.loads(json_data)
        
        evidence_chain = self.import_evidence_chain(json.dumps(data["evidence_chain"]))
        
        return InvestigationReport(
            report_id=data["report_id"],
            change_event_id=data["change_event_id"],
            summary=data["summary"],
            findings=data["findings"],
            conclusions=data["conclusions"],
            recommendations=data["recommendations"],
            evidence_chain=evidence_chain,
            risk_assessment=data["risk_assessment"],
            generated_at=data["generated_at"]
        )
